### ISSUE TITLE
Unpredictable testing output

### ISSUE THREAD

**Issue by Guppster** [ArkEcosystem/ark-java#13]
I have been running the test suite and running into `Connection to {ip} refused` on different tests each time. When run repetitively, it's a random chance to get a pass or fail. Sometimes all tests pass, sometimes random ones fail to connect

This is pretty bad because i don't know if my code changes broke the library or not.

**Comment by Guppster** [comment]
I found out this is because of many unresponsive peers hard coded into the library. This was also the reason for very slow tests because each peer was timing out slowly.

Since the tests used the randomPeer method, there was a random chance of getting a working or broken peer

**Comment by ehrlichja** [comment]
can we solve this with mocks?
