### ISSUE TITLE
Create stub node for integration tests

### ISSUE THREAD

**Issue by dafty** [ArkEcosystem/ark-java#22]
Tests currently uses live networks to test, eg:

```
def result = peer << transaction
  then:
  result.error == "Account does not have enough ARK: AGeYmgbg2LgGxRW2vNNJvQ88PknEJsYizC balance: 0"
```

sending some Ark to that address will cause a lot of tests to fail.

```
result.get("success") == true
result.get("count").equals("2") //Count doesnt include filtering from api call
(result.get("transactions") as List).size() == 2
```

or sending a tx to this address will cause this to fail.

We should create a stub node with the same validation on ark-node, but provide controlled variables (balance, votes, transactions, etc) and replace affected tests to use that instead.

**Comment by Guppster** [comment]
I am currently working on this, I'll create a PR in a few days

**Comment by dafty** [comment]
https://github.com/ArkEcosystem/ark-java/commit/f2fed88789db6a93c5b7e72c469d99214a4d3d98
