### ISSUE TITLE
Vote Transaction problem

### ISSUE THREAD

**Issue by bhaaltazar** [ArkEcosystem/ark-java#5]
For exampe try to vote for arkpool. 
Transaction.createVote(["+02b1d2ea7c265db66087789f571fceb8cc2b2d89e296ad966efb8ed51855f2ae0b"], passphrase)

I get:
Transaction not accepted by network:
[success:false, message:Invalid transaction detected, error:Invalid recipient]

Why Invalid recipient? We have only two parameters in Transaction.createVote() method, votes array and passphrase. Can somebody check it works or not, seems a bug.

**Comment by fix** [comment]
ah true that, will fix it.

In the between, just do before sending tx
```
tx.recipientId = "the address of the tx sender"
tx.sign(passphrase)
tx.id = Crypto.getId(tx)
```
a bug in the protocol i will address next month

**Comment by bhaaltazar** [comment]
@fix it works, thank you!

**Comment by bhaaltazar** [comment]
@fix also have problem with setting up second passphrase:
`Transaction.createSecondSignature("passphrase2", "passphrase")`
Get message:
> Transaction not accepted by network:
[success:false, message:Invalid transaction detected, error:TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.]

Created separate issue here https://github.com/ArkEcosystem/ark-java/issues/6
